services:
  - docker

language: generic

script:
  - make build

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=oinker/oinker-oauth
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO

env:
  global:
    - secure: "W5UVisoB3HwZrVkzJ2lOZJTwo1bXZv62oFDmLTPXQq0yOAae0sAskMF6ESRnzPqe0S5yjgo9nsdtqdJ30mH7CvtKoGzLSkh9Ijs4EbgpSzcXdFV72pee69F7YmgaeLFrgroWVKqMTVKRypngqHQ8wl9nuOreJquZ5zQz7xP9vug/nwyZ+kdBDGJYJ0ztxHtjqD856VtLMmpThe2j7ok5ThILSSh42bRICUsfHd7pvK7mihlO973D7G+BYODRsQueeXdV/G85b7OkNafIwx6+ZqhDw7cABtRb66WKh6xkErUNSydHepYU2eIQeYlYfyadf01iKZIie50+u2TEVFkQzDoMj+s5NmaBPHtMwZ+Kq7X97+IPkEatlgiJBOM3BCVzBLG/dZCYZa84nRnhEosXLuKP9ThHr25Hi/c1MPlA0ca0NqWvjCM8QupAXwlnxTO31XnCkUQiezM6Sv/Bu2TexT/5HR37Y2DUT8x0OUH3MUnHX/x2GMOBjVILI2WR8zzHOWcpWHOgT5oo/oWq+qKAXdJlbQqzFY5o5tV5x7T2WPGSWCbZXQRzrHZ2H9tmh4yOV8AeWYkqqLaiwFGi87qzOhxs+EVXHVYTe0y3Boi3e+ZKNeIrsg8mhkyl8ddtz+z7TDbG+UJrT7I6Sh9BW6tPzhoeo308xpaeITKcsdGxNfw=" # DOCKER_EMAIL
    - secure: "RYzJTqCv3WUAkLmniySY4Yge7VkZg55OW8chpMBceQ8jEZY1JWkHs2ejiTqM7jGC39+tdMu1iAexTm+GiL2T9ckMTQcZzRHNTOyzQ+09UQvcBqbQHbX3T+rH8aqSJxRsIryIwUtFPhRAjYSi1AVgeHc2TDrBxcRYJAjwtdGlQ8/OPE6BXBpgvJQbLs2gjaSYdNYddWvh6gtPEQglG9o/biONZddezB6SGFxoKiWUFsDHEsEhTU7pLys88aW6RJa1xsmI8pTsiuKkTbJP/8bKLVwUuFaabWhvqETND5i21SfsVa0KjgRVwEisj6D91OjUUf3JZ8MnXoA7DapH1pZaZOMEeOlncIc8m8pus1cB1pJimMrqluo3jwImdNPrg6h0joIxYKxMoncvMv7N3r3tIyESHk9Va/CI0uoNl4gMCEQBGyaqouJbE3zjHNA7bZwKwr957J9+4T8FQRhbivEr1fH6pQ6EaWMOo/g9YcI87k32z9IrtcLeexL/hKY+SbH3Kut0P7nHKVFr4CUbmYMSm7SSNhts9r6oyoCnByxPcCDKUM/lX6+94ZExxiwBggLd37Pfka1z2m9nmspuEmltPSYCop9FRT5kLKFn6SP2KBUn+SafosYXDuYNBQeh3dz39EpA3y8WdtbdJ/hec1rnlmdVdyWUwpJQ9nzuMe4uK50=" # DOCKER_USER
    - secure: "HIehEMkNAagCyBTSk88i7BQSb8OMXvW4zblygfhWiEdAcJVLQm+4vM9AcLHfgrlOmSWNVwFkfC1R7wSV2Y3rzZVcHhhO2u1c2uPQhM/mNQTLyjJggTxjk9KPbDVbdt5Isbs1vydApUvhpu1AME/Cnj+3OWzvhTqP6pQJO5bw/HdNghhwoTbFHFls+oNupg55WEOlfI79tIhveqhIRdPoZmWfX/REHPQN2xrwriNue9n7NCUuiTZcqldeRqMy0bzgd/n/jnDuC0DlGJzuINt+dk1K0Pxy/CZj86zmQvGXrBTueM/XCCsciUwLVJ8PA21ky8eWV0FrzrPpc/5bPp35G9C7EwfzyMVhSjcWb0155FZdxjbi4iCICGLYpftayvNAYgDbYRMzxoHCSRoTUAJgfSW4TeHI0muBXpUgp1YJVvMrQWlTFZIrdxOvmfJseNfudrr/YSzmgHNOYsw63nrqEVfzGGDyuZIbp817MGk20LeeF5rWG93hVMXB7QD7pEqMQ/2Di6SXEbdqJ6SrOs7uUCCWfh0VPnVAbrYjA5g0Ikh1uLaII289vmUWFOMOlEmM0et2TGv8L11W4Tl0VFE3uUv2EX9BsmJd7Sel3tJMD+V2P4sjzo72uCmwbXcO4pEs63TawOSqzVlMURc8pOSxMw/3MrktUDX1Vf9/KfrWruY=" # DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::8}