services:
  - docker

language: generic

script:
  - make build

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=oinker/oinker-oauth
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker push $REPO

env:
  global:
    - secure: "iC8adzuds8XsgpimMkZeKQ/48BH5LKKetS5apUpECiGij5+AF1vqom4whjDquGHMiuJxAmvgXMMVcsFKd/nHdUX80Eh26bGnUXhQwWna1Xw7ge6q3QTiPFTTDfGSn9O4i3TcUDkkYkG0dhj2chtBvVkTu3WrjoTPPMBSpIEMDp3Bdc2HuefZLH1uB9DUPW0/MxvZNQWPHg8mJ+kK8fG0bZua788EN+6o7oWvraGLWC5HEU9PW+fsExPnBgwPJB6PkZ+89prKDe9aWLv55YawNfdfaamW7cWd9PRXbFj8S/g1OMRUx3PblqEyR+ZQrZFcfJR2nkzO1rEAlaZAmzb4HZIWaKBjTL35wO1OF9KFfz6Ju6SKV0reOsw7yQmjl8cKYo2SrqUG+0yCOTcGVl6GMqBYGbBN85kWzFNuQCxIJGKH9r9hQl3o2ULKN1QSFCzCgEU1XjX7VKk4HudxuvU449Jrap/BjyXnDVois8IRTZi6N/TBKDsvxnKfZh/W1EpiHInj5ns01IoP5qJW/szmSyR4C4K7oPJCW81GmoeL4BQOP/hsy9A+fRInl86iirxWh/JXAwCCrUPXx2Uo+BGjggPwWxNxG37sgEwNU02oY06CEEIOLVaopwNxGFq6epoVB0vQJA6X2M2/3JKHPliriJyTRgKG/4/d+3BduCE0WV8=" # DOCKER_EMAIL
    - secure: "Le1h70j74x1onqIsw2Df256UYqfhoknXvlhYi8v+9UhlbxIdyxEALI+FEFDxVmbvviScvogLO+BEtXd2UCcoZS6E/qsinMRlX17dX0RjzCCnQK0hcornHJDAumgiQaLKV0ukEEwpJ+/KoK650BT3W947Cf6JOlQEDYCSNpy86ySLQcBkDm5+1x5AEEXd9Dfbxdq1LltFJyJye0lUuRiiLhaer3ADWA70jgAX7lDFOdIhfRf9kjrW5HqWBy/tbjJ3sIyNO7qWB2aIMbFO4gWY1H5Hy8li0AOWkNGYUxASgiVpkKDCtwAkwC4gXKDJdvEJ/s9V/5BICUJkhuRh6q72hECSLwePIk4K7UXwiPKF7c8py5sV4UAujvu4cBT/j9Df7c4iTKWB1+5yzx86mhBt/MQQGaUtKT8a+CORBAIcncKDxGpT3iW9rp/dPwIg30LIF7hRx3udcGb11M7eYW6+etVQCKeW5Z89RsaSDzFVVln8GDFGrTUsSZ1R7gpCB2X8XzXlyUGuXSlzi/fG1Gv/vCMBhjQJ2doXFhtGxy+JeTmC1vgin/HgyS6lPue/XmgPgX5S9srirR5TFyPXyHl+TBa427PuEty1HnurbnvXtOpHP/eNwrXk5pccssUisAi+IRUQp1cuo4bnHEiORMgnVwUyxXa2Fa8oM0VPNfOC1IY=" # DOCKER_USER
    - secure: "BlF92oO7PZRHdeEWpo+4UVxInJzhKPU5w77xo+Cw2I8OvZVXETmLBvozJ7o8itOTyEmwo7mbKjKRP9yFhwjmXa1XQTW5Rc43okj+3t3MAKoPkkhMlOy5Zrzj1RjGrHM7HD36SteV2RHV+tIXwyUtf/4Knx9H4Tv9a4ZQDpllluCfBrZDvyTYY7pBmPAg8OmswC2ZmY7dy7LUl4jEH1+BEdPF3O/y6wJvmwfEbZ2bcrzACOTS3CfnSr32eUjuVteXRSUU3+eyN3cRtDy/sZ2KwFJxiIyb7HkffYP70EQ7Lriezc3X+td4gQD4UUNUe5ZCvy4+o5h5xTEICn8h/7K6YsiugwBpF/U89HZ4OUMw9twy5RJFl+Z5AmGdF3+oqkVPXBOpHzfYUHl+jRxxdhM64v1d65YAeoYe3JOuLp3+EOkQF3VpBjoXEqYNQqM7LhBlohRkTop0RYX4WTqCh0E7kwThssARplid0FEPuBRlrsxOkZrNRu8Xpl9NgshFiAFpJNJ8EE6ZFhwf91/kmxJ9M/W00KnFrs9JXT5JwkgWB15BzEh48tejTPPjKZFSOpCsQUSSZvREbsARJ68t7zpj4X+Gx6vgkrvjhyPU8u3wnROWWoJ3MnHpmh/2Z1bl1DMqNHgVtIZ/obFbDM+fW1EFDjCLenRmuj1gOWnEd10/ink=" # DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::6}