version: '2'

services:
  dev:
    image: oinker/oinker_admin
    ports:
      - 8091:80
    volumes:
      - ./src/public:/var/www/html
    environment:
        - API_BASE_URI=http://#/api/v1
        - SECONDS_BETWEEN_LOGIN_TRIES=7
        - SECONDS_FIRST_LOGIN_TRY=7
        - MAINTENANCE_MODE=0
        - OAUTH_SECRET=#

